server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  config:
    import: "optional:configserver:http://${CONFIG_SERVER_URI:localhost:8888}"
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false  # Manuel route tanımı kullanıyoruz

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: false
    hostname: localhost

jwt:
  secret: ${JWT_SECRET:ecommerce-super-secret-jwt-key-minimum-256-bits-long-change-in-prod}
  access-token-expiration-ms: 900000
  refresh-token-expiration-ms: 604800000

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: INFO
    com.ecommerce.gateway: DEBUG
