server:
  port: 8081

spring:
  application:
    name: user-service
  config:
    import: "optional:configserver:http://${CONFIG_SERVER_URI:localhost:8888}"

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: false
    hostname: localhost
    lease-renewal-interval-in-seconds: 10

jwt:
  secret: ${JWT_SECRET:ecommerce-super-secret-jwt-key-minimum-256-bits-long-change-in-prod}
  access-token-expiration-ms: 900000
  refresh-token-expiration-ms: 604800000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
