spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/ecommerce_cart_db
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
