spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/ecommerce_payment_db
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

iyzico:
  api-key: ${IYZICO_API_KEY:sandbox-79J39ggYDjlvWyib5Nyleyo8bTqJsDPA}
  secret-key: ${IYZICO_SECRET_KEY:sandbox-DKTW3UZZoLkUPPa2GQyvXMiPB3zc4Iod}
  base-url: ${IYZICO_BASE_URL:https://sandbox-api.iyzipay.com}

app:
  callback-url: ${APP_CALLBACK_URL:http://130.61.124.247:8080/api/payments/callback}
  frontend-url: ${APP_FRONTEND_URL:https://n55-frontend.vercel.app}

rabbitmq:
  exchange: ecommerce.events
  routing-keys:
    payment-completed: payment.completed
    payment-failed: payment.failed

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    config-url: /payment-service/v3/api-docs/swagger-config
    url: /payment-service/v3/api-docs
